services:
  express_app:
    build:
      dockerfile: docker/express-app.dockerfile
      context: .

  caddy:
    build:
      dockerfile: docker/caddy.dockerfile
      context: .
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
