---
- name: Setup repo on server with ci/cd
  hosts: all
  vars:
    cf_api_token: "{{ lookup('ansible.builtin.env', 'CF_API_TOKEN') }}"
    ansible_python_interpreter: /usr/bin/python3.12
  
  tasks:
    - name: Create necessary directory
      ansible.builtin.file:
        path: ~/{{ item }}
        state: directory
      with_items:
        - services
        - automation

    - name: Clone the repo
      ansible.builtin.git:
        repo: 'https://github.com/MdNaina/vps-ci-cd-starter.git'
        dest: ~/services/project

    - name: Copy automation files to automation
      ansible.builtin.copy:
        src: ./files/automation.sh
        dest: ~/automation/deploy.sh
        mode: u+rwx

    - name: Start project with Docker Compose
      community.docker.docker_compose_v2:
        project_src: ~/services/project
      environment:
        CF_API_TOKEN: "{{ cf_api_token }}"
      register: output

    - name: Setup CI/CD pipeline
      ansible.builtin.cron:
        name: "Setup deploy cron job for CI/CD"
        job: ~/automation/deploy.sh

